header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Zigflow authors <https://github.com/zigflow/ui/graphs/contributors>
    copyright-year: 2025 - 2026
  paths-ignore:
    - '**/dist'
    - '**/tmp'
    - LICENSE
    - '**/.*'
    - '**/go.*'
    - '**/*.{json,md,yml,yaml,txt}'
    - '**/.gitkeep'
    - '**/*.svelte'
  comment: on-failure

dependency:
  files:
    - package.json # If this is a npm project.
